// DO NOT EDIT. generated by webtyp.com/ormc

package appointmentbooking

import (
	"webtyp.com/model"
	"webtyp.com/orm"
)

type EmployeeServiceConfig struct {
	Id string
	TenantId string
	StaffId string
	ServiceId string
	DurationMin int64
	BufferMin int64
	PriceOverride float64
	PaymentRequired bool
	IsActive bool
}

func (m *EmployeeServiceConfig) ModelName() string { return "employee_service_config" }

func (m *EmployeeServiceConfig) Schema() []model.Field { return EmployeeServiceConfigModel.Fields }

func (m *EmployeeServiceConfig) Pointers() []any { return []any{&m.Id, &m.TenantId, &m.StaffId, &m.ServiceId, &m.DurationMin, &m.BufferMin, &m.PriceOverride, &m.PaymentRequired, &m.IsActive} }

func (m *EmployeeServiceConfig) IsNil() bool { return m == nil }

func (m *EmployeeServiceConfig) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.String("tenant_id", m.TenantId)
	w.String("staff_id", m.StaffId)
	w.String("service_id", m.ServiceId)
	w.Int("duration_min", m.DurationMin)
	w.Int("buffer_min", m.BufferMin)
	w.Float("price_override", m.PriceOverride)
	w.Bool("payment_required", m.PaymentRequired)
	w.Bool("is_active", m.IsActive)
}

func (m *EmployeeServiceConfig) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("staff_id"); ok { m.StaffId = v }
	if v, ok := r.String("service_id"); ok { m.ServiceId = v }
	if v, ok := r.Int("duration_min"); ok { m.DurationMin = v }
	if v, ok := r.Int("buffer_min"); ok { m.BufferMin = v }
	if v, ok := r.Float("price_override"); ok { m.PriceOverride = v }
	if v, ok := r.Bool("payment_required"); ok { m.PaymentRequired = v }
	if v, ok := r.Bool("is_active"); ok { m.IsActive = v }
}

type EmployeeServiceConfigList []*EmployeeServiceConfig

func (s *EmployeeServiceConfigList) Len() int             { return len(*s) }
func (s *EmployeeServiceConfigList) At(i int) model.Fielder { return (*s)[i] }
func (s *EmployeeServiceConfigList) Append() model.Fielder  { v := &EmployeeServiceConfig{}; *s = append(*s, v); return v }
func (s *EmployeeServiceConfigList) IsNil() bool          { return s == nil }
func (s *EmployeeServiceConfigList) EncodeFields(_ model.FieldWriter) {}
func (s *EmployeeServiceConfigList) DecodeFields(_ model.FieldReader) {}

func (m *EmployeeServiceConfig) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var EmployeeServiceConfig_ = struct {
	Id string
	TenantId string
	StaffId string
	ServiceId string
	DurationMin string
	BufferMin string
	PriceOverride string
	PaymentRequired string
	IsActive string
}{
	Id: "id",
	TenantId: "tenant_id",
	StaffId: "staff_id",
	ServiceId: "service_id",
	DurationMin: "duration_min",
	BufferMin: "buffer_min",
	PriceOverride: "price_override",
	PaymentRequired: "payment_required",
	IsActive: "is_active",
}

func ReadOneEmployeeServiceConfig(qb *orm.QB, model *EmployeeServiceConfig) (*EmployeeServiceConfig, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllEmployeeServiceConfig(qb *orm.QB) (EmployeeServiceConfigList, error) {
	var results EmployeeServiceConfigList
	err := qb.ReadAll(
		func() model.Model { return &EmployeeServiceConfig{} },
		func(m model.Model) { results = append(results, m.(*EmployeeServiceConfig)) },
	)
	return results, err
}

type WorkCalendarConfig struct {
	Id string
	TenantId string
	StaffId string
	Timezone string
	IsActive bool
}

func (m *WorkCalendarConfig) ModelName() string { return "work_calendar_config" }

func (m *WorkCalendarConfig) Schema() []model.Field { return WorkCalendarConfigModel.Fields }

func (m *WorkCalendarConfig) Pointers() []any { return []any{&m.Id, &m.TenantId, &m.StaffId, &m.Timezone, &m.IsActive} }

func (m *WorkCalendarConfig) IsNil() bool { return m == nil }

func (m *WorkCalendarConfig) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.String("tenant_id", m.TenantId)
	w.String("staff_id", m.StaffId)
	w.String("timezone", m.Timezone)
	w.Bool("is_active", m.IsActive)
}

func (m *WorkCalendarConfig) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("staff_id"); ok { m.StaffId = v }
	if v, ok := r.String("timezone"); ok { m.Timezone = v }
	if v, ok := r.Bool("is_active"); ok { m.IsActive = v }
}

type WorkCalendarConfigList []*WorkCalendarConfig

func (s *WorkCalendarConfigList) Len() int             { return len(*s) }
func (s *WorkCalendarConfigList) At(i int) model.Fielder { return (*s)[i] }
func (s *WorkCalendarConfigList) Append() model.Fielder  { v := &WorkCalendarConfig{}; *s = append(*s, v); return v }
func (s *WorkCalendarConfigList) IsNil() bool          { return s == nil }
func (s *WorkCalendarConfigList) EncodeFields(_ model.FieldWriter) {}
func (s *WorkCalendarConfigList) DecodeFields(_ model.FieldReader) {}

func (m *WorkCalendarConfig) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var WorkCalendarConfig_ = struct {
	Id string
	TenantId string
	StaffId string
	Timezone string
	IsActive string
}{
	Id: "id",
	TenantId: "tenant_id",
	StaffId: "staff_id",
	Timezone: "timezone",
	IsActive: "is_active",
}

func ReadOneWorkCalendarConfig(qb *orm.QB, model *WorkCalendarConfig) (*WorkCalendarConfig, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllWorkCalendarConfig(qb *orm.QB) (WorkCalendarConfigList, error) {
	var results WorkCalendarConfigList
	err := qb.ReadAll(
		func() model.Model { return &WorkCalendarConfig{} },
		func(m model.Model) { results = append(results, m.(*WorkCalendarConfig)) },
	)
	return results, err
}

type WorkCalendarBlock struct {
	Id string
	TenantId string
	StaffId string
	DayOfWeek int64
	SpecificDate int64
	StartMin int64
	EndMin int64
	IsActive bool
}

func (m *WorkCalendarBlock) ModelName() string { return "work_calendar_block" }

func (m *WorkCalendarBlock) Schema() []model.Field { return WorkCalendarBlockModel.Fields }

func (m *WorkCalendarBlock) Pointers() []any { return []any{&m.Id, &m.TenantId, &m.StaffId, &m.DayOfWeek, &m.SpecificDate, &m.StartMin, &m.EndMin, &m.IsActive} }

func (m *WorkCalendarBlock) IsNil() bool { return m == nil }

func (m *WorkCalendarBlock) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.String("tenant_id", m.TenantId)
	w.String("staff_id", m.StaffId)
	w.Int("day_of_week", m.DayOfWeek)
	w.Int("specific_date", m.SpecificDate)
	w.Int("start_min", m.StartMin)
	w.Int("end_min", m.EndMin)
	w.Bool("is_active", m.IsActive)
}

func (m *WorkCalendarBlock) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("staff_id"); ok { m.StaffId = v }
	if v, ok := r.Int("day_of_week"); ok { m.DayOfWeek = v }
	if v, ok := r.Int("specific_date"); ok { m.SpecificDate = v }
	if v, ok := r.Int("start_min"); ok { m.StartMin = v }
	if v, ok := r.Int("end_min"); ok { m.EndMin = v }
	if v, ok := r.Bool("is_active"); ok { m.IsActive = v }
}

type WorkCalendarBlockList []*WorkCalendarBlock

func (s *WorkCalendarBlockList) Len() int             { return len(*s) }
func (s *WorkCalendarBlockList) At(i int) model.Fielder { return (*s)[i] }
func (s *WorkCalendarBlockList) Append() model.Fielder  { v := &WorkCalendarBlock{}; *s = append(*s, v); return v }
func (s *WorkCalendarBlockList) IsNil() bool          { return s == nil }
func (s *WorkCalendarBlockList) EncodeFields(_ model.FieldWriter) {}
func (s *WorkCalendarBlockList) DecodeFields(_ model.FieldReader) {}

func (m *WorkCalendarBlock) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var WorkCalendarBlock_ = struct {
	Id string
	TenantId string
	StaffId string
	DayOfWeek string
	SpecificDate string
	StartMin string
	EndMin string
	IsActive string
}{
	Id: "id",
	TenantId: "tenant_id",
	StaffId: "staff_id",
	DayOfWeek: "day_of_week",
	SpecificDate: "specific_date",
	StartMin: "start_min",
	EndMin: "end_min",
	IsActive: "is_active",
}

func ReadOneWorkCalendarBlock(qb *orm.QB, model *WorkCalendarBlock) (*WorkCalendarBlock, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllWorkCalendarBlock(qb *orm.QB) (WorkCalendarBlockList, error) {
	var results WorkCalendarBlockList
	err := qb.ReadAll(
		func() model.Model { return &WorkCalendarBlock{} },
		func(m model.Model) { results = append(results, m.(*WorkCalendarBlock)) },
	)
	return results, err
}

type WorkCalendarException struct {
	Id string
	TenantId string
	StaffId string
	SpecificDate int64
	ExceptionType string
	StartTime int64
	EndTime int64
	Notes string
}

func (m *WorkCalendarException) ModelName() string { return "work_calendar_exception" }

func (m *WorkCalendarException) Schema() []model.Field { return WorkCalendarExceptionModel.Fields }

func (m *WorkCalendarException) Pointers() []any { return []any{&m.Id, &m.TenantId, &m.StaffId, &m.SpecificDate, &m.ExceptionType, &m.StartTime, &m.EndTime, &m.Notes} }

func (m *WorkCalendarException) IsNil() bool { return m == nil }

func (m *WorkCalendarException) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.String("tenant_id", m.TenantId)
	w.String("staff_id", m.StaffId)
	w.Int("specific_date", m.SpecificDate)
	w.String("exception_type", m.ExceptionType)
	w.Int("start_time", m.StartTime)
	w.Int("end_time", m.EndTime)
	w.String("notes", m.Notes)
}

func (m *WorkCalendarException) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("staff_id"); ok { m.StaffId = v }
	if v, ok := r.Int("specific_date"); ok { m.SpecificDate = v }
	if v, ok := r.String("exception_type"); ok { m.ExceptionType = v }
	if v, ok := r.Int("start_time"); ok { m.StartTime = v }
	if v, ok := r.Int("end_time"); ok { m.EndTime = v }
	if v, ok := r.String("notes"); ok { m.Notes = v }
}

type WorkCalendarExceptionList []*WorkCalendarException

func (s *WorkCalendarExceptionList) Len() int             { return len(*s) }
func (s *WorkCalendarExceptionList) At(i int) model.Fielder { return (*s)[i] }
func (s *WorkCalendarExceptionList) Append() model.Fielder  { v := &WorkCalendarException{}; *s = append(*s, v); return v }
func (s *WorkCalendarExceptionList) IsNil() bool          { return s == nil }
func (s *WorkCalendarExceptionList) EncodeFields(_ model.FieldWriter) {}
func (s *WorkCalendarExceptionList) DecodeFields(_ model.FieldReader) {}

func (m *WorkCalendarException) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var WorkCalendarException_ = struct {
	Id string
	TenantId string
	StaffId string
	SpecificDate string
	ExceptionType string
	StartTime string
	EndTime string
	Notes string
}{
	Id: "id",
	TenantId: "tenant_id",
	StaffId: "staff_id",
	SpecificDate: "specific_date",
	ExceptionType: "exception_type",
	StartTime: "start_time",
	EndTime: "end_time",
	Notes: "notes",
}

func ReadOneWorkCalendarException(qb *orm.QB, model *WorkCalendarException) (*WorkCalendarException, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllWorkCalendarException(qb *orm.QB) (WorkCalendarExceptionList, error) {
	var results WorkCalendarExceptionList
	err := qb.ReadAll(
		func() model.Model { return &WorkCalendarException{} },
		func(m model.Model) { results = append(results, m.(*WorkCalendarException)) },
	)
	return results, err
}

type Reservation struct {
	Id string
	TenantId string
	ClientId string
	CreatorUserId string
	EmployeeServiceConfigId string
	StaffIdsnapshot string
	ServiceIdsnapshot string
	DurationMinSnapshot int64
	PriceSnapshot float64
	CurrencySnapshot string
	ReservationDate int64
	ReservationTime int64
	LocalStringDate string
	LocalStringTime string
	Status string
	RescheduledFromId string
	StatusBeforeConflict string
	PaymentId string
	Notes string
	UpdatedAt int64
	UpdatedBy string
	Revision int64
}

func (m *Reservation) ModelName() string { return "reservation" }

func (m *Reservation) Schema() []model.Field { return ReservationModel.Fields }

func (m *Reservation) Pointers() []any { return []any{&m.Id, &m.TenantId, &m.ClientId, &m.CreatorUserId, &m.EmployeeServiceConfigId, &m.StaffIdsnapshot, &m.ServiceIdsnapshot, &m.DurationMinSnapshot, &m.PriceSnapshot, &m.CurrencySnapshot, &m.ReservationDate, &m.ReservationTime, &m.LocalStringDate, &m.LocalStringTime, &m.Status, &m.RescheduledFromId, &m.StatusBeforeConflict, &m.PaymentId, &m.Notes, &m.UpdatedAt, &m.UpdatedBy, &m.Revision} }

func (m *Reservation) IsNil() bool { return m == nil }

func (m *Reservation) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.String("tenant_id", m.TenantId)
	w.String("client_id", m.ClientId)
	w.String("creator_user_id", m.CreatorUserId)
	w.String("employee_service_config_id", m.EmployeeServiceConfigId)
	w.String("staff_idsnapshot", m.StaffIdsnapshot)
	w.String("service_idsnapshot", m.ServiceIdsnapshot)
	w.Int("duration_min_snapshot", m.DurationMinSnapshot)
	w.Float("price_snapshot", m.PriceSnapshot)
	w.String("currency_snapshot", m.CurrencySnapshot)
	w.Int("reservation_date", m.ReservationDate)
	w.Int("reservation_time", m.ReservationTime)
	w.String("local_string_date", m.LocalStringDate)
	w.String("local_string_time", m.LocalStringTime)
	w.String("status", m.Status)
	w.String("rescheduled_from_id", m.RescheduledFromId)
	w.String("status_before_conflict", m.StatusBeforeConflict)
	w.String("payment_id", m.PaymentId)
	w.String("notes", m.Notes)
	w.Int("updated_at", m.UpdatedAt)
	w.String("updated_by", m.UpdatedBy)
	w.Int("revision", m.Revision)
}

func (m *Reservation) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("client_id"); ok { m.ClientId = v }
	if v, ok := r.String("creator_user_id"); ok { m.CreatorUserId = v }
	if v, ok := r.String("employee_service_config_id"); ok { m.EmployeeServiceConfigId = v }
	if v, ok := r.String("staff_idsnapshot"); ok { m.StaffIdsnapshot = v }
	if v, ok := r.String("service_idsnapshot"); ok { m.ServiceIdsnapshot = v }
	if v, ok := r.Int("duration_min_snapshot"); ok { m.DurationMinSnapshot = v }
	if v, ok := r.Float("price_snapshot"); ok { m.PriceSnapshot = v }
	if v, ok := r.String("currency_snapshot"); ok { m.CurrencySnapshot = v }
	if v, ok := r.Int("reservation_date"); ok { m.ReservationDate = v }
	if v, ok := r.Int("reservation_time"); ok { m.ReservationTime = v }
	if v, ok := r.String("local_string_date"); ok { m.LocalStringDate = v }
	if v, ok := r.String("local_string_time"); ok { m.LocalStringTime = v }
	if v, ok := r.String("status"); ok { m.Status = v }
	if v, ok := r.String("rescheduled_from_id"); ok { m.RescheduledFromId = v }
	if v, ok := r.String("status_before_conflict"); ok { m.StatusBeforeConflict = v }
	if v, ok := r.String("payment_id"); ok { m.PaymentId = v }
	if v, ok := r.String("notes"); ok { m.Notes = v }
	if v, ok := r.Int("updated_at"); ok { m.UpdatedAt = v }
	if v, ok := r.String("updated_by"); ok { m.UpdatedBy = v }
	if v, ok := r.Int("revision"); ok { m.Revision = v }
}

type ReservationList []*Reservation

func (s *ReservationList) Len() int             { return len(*s) }
func (s *ReservationList) At(i int) model.Fielder { return (*s)[i] }
func (s *ReservationList) Append() model.Fielder  { v := &Reservation{}; *s = append(*s, v); return v }
func (s *ReservationList) IsNil() bool          { return s == nil }
func (s *ReservationList) EncodeFields(_ model.FieldWriter) {}
func (s *ReservationList) DecodeFields(_ model.FieldReader) {}

func (m *Reservation) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var Reservation_ = struct {
	Id string
	TenantId string
	ClientId string
	CreatorUserId string
	EmployeeServiceConfigId string
	StaffIdsnapshot string
	ServiceIdsnapshot string
	DurationMinSnapshot string
	PriceSnapshot string
	CurrencySnapshot string
	ReservationDate string
	ReservationTime string
	LocalStringDate string
	LocalStringTime string
	Status string
	RescheduledFromId string
	StatusBeforeConflict string
	PaymentId string
	Notes string
	UpdatedAt string
	UpdatedBy string
	Revision string
}{
	Id: "id",
	TenantId: "tenant_id",
	ClientId: "client_id",
	CreatorUserId: "creator_user_id",
	EmployeeServiceConfigId: "employee_service_config_id",
	StaffIdsnapshot: "staff_idsnapshot",
	ServiceIdsnapshot: "service_idsnapshot",
	DurationMinSnapshot: "duration_min_snapshot",
	PriceSnapshot: "price_snapshot",
	CurrencySnapshot: "currency_snapshot",
	ReservationDate: "reservation_date",
	ReservationTime: "reservation_time",
	LocalStringDate: "local_string_date",
	LocalStringTime: "local_string_time",
	Status: "status",
	RescheduledFromId: "rescheduled_from_id",
	StatusBeforeConflict: "status_before_conflict",
	PaymentId: "payment_id",
	Notes: "notes",
	UpdatedAt: "updated_at",
	UpdatedBy: "updated_by",
	Revision: "revision",
}

func ReadOneReservation(qb *orm.QB, model *Reservation) (*Reservation, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllReservation(qb *orm.QB) (ReservationList, error) {
	var results ReservationList
	err := qb.ReadAll(
		func() model.Model { return &Reservation{} },
		func(m model.Model) { results = append(results, m.(*Reservation)) },
	)
	return results, err
}

type TimeSlot struct {
	StartUtc int64
	EndUtc int64
}

func (m *TimeSlot) ModelName() string { return "time_slot" }

func (m *TimeSlot) Schema() []model.Field { return TimeSlotModel.Fields }

func (m *TimeSlot) Pointers() []any { return []any{&m.StartUtc, &m.EndUtc} }

func (m *TimeSlot) IsNil() bool { return m == nil }

func (m *TimeSlot) EncodeFields(w model.FieldWriter) {
	w.Int("start_utc", m.StartUtc)
	w.Int("end_utc", m.EndUtc)
}

func (m *TimeSlot) DecodeFields(r model.FieldReader) {
	if v, ok := r.Int("start_utc"); ok { m.StartUtc = v }
	if v, ok := r.Int("end_utc"); ok { m.EndUtc = v }
}

type TimeSlotList []*TimeSlot

func (s *TimeSlotList) Len() int             { return len(*s) }
func (s *TimeSlotList) At(i int) model.Fielder { return (*s)[i] }
func (s *TimeSlotList) Append() model.Fielder  { v := &TimeSlot{}; *s = append(*s, v); return v }
func (s *TimeSlotList) IsNil() bool          { return s == nil }
func (s *TimeSlotList) EncodeFields(_ model.FieldWriter) {}
func (s *TimeSlotList) DecodeFields(_ model.FieldReader) {}

func (m *TimeSlot) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type CreateReservationArgs struct {
	TenantId string
	ClientId string
	CreatorUserId string
	EmployeeServiceConfigId string
	SlotStartUtc int64
	Notes string
	RescheduledFromId string
}

func (m *CreateReservationArgs) ModelName() string { return "create_reservation_args" }

func (m *CreateReservationArgs) Schema() []model.Field { return CreateReservationArgsModel.Fields }

func (m *CreateReservationArgs) Pointers() []any { return []any{&m.TenantId, &m.ClientId, &m.CreatorUserId, &m.EmployeeServiceConfigId, &m.SlotStartUtc, &m.Notes, &m.RescheduledFromId} }

func (m *CreateReservationArgs) IsNil() bool { return m == nil }

func (m *CreateReservationArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("client_id", m.ClientId)
	w.String("creator_user_id", m.CreatorUserId)
	w.String("employee_service_config_id", m.EmployeeServiceConfigId)
	w.Int("slot_start_utc", m.SlotStartUtc)
	w.String("notes", m.Notes)
	w.String("rescheduled_from_id", m.RescheduledFromId)
}

func (m *CreateReservationArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("client_id"); ok { m.ClientId = v }
	if v, ok := r.String("creator_user_id"); ok { m.CreatorUserId = v }
	if v, ok := r.String("employee_service_config_id"); ok { m.EmployeeServiceConfigId = v }
	if v, ok := r.Int("slot_start_utc"); ok { m.SlotStartUtc = v }
	if v, ok := r.String("notes"); ok { m.Notes = v }
	if v, ok := r.String("rescheduled_from_id"); ok { m.RescheduledFromId = v }
}

type CreateReservationArgsList []*CreateReservationArgs

func (s *CreateReservationArgsList) Len() int             { return len(*s) }
func (s *CreateReservationArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *CreateReservationArgsList) Append() model.Fielder  { v := &CreateReservationArgs{}; *s = append(*s, v); return v }
func (s *CreateReservationArgsList) IsNil() bool          { return s == nil }
func (s *CreateReservationArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *CreateReservationArgsList) DecodeFields(_ model.FieldReader) {}

func (m *CreateReservationArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type GetReservationArgs struct {
	TenantId string
	Id string
}

func (m *GetReservationArgs) ModelName() string { return "get_reservation_args" }

func (m *GetReservationArgs) Schema() []model.Field { return GetReservationArgsModel.Fields }

func (m *GetReservationArgs) Pointers() []any { return []any{&m.TenantId, &m.Id} }

func (m *GetReservationArgs) IsNil() bool { return m == nil }

func (m *GetReservationArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("id", m.Id)
}

func (m *GetReservationArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("id"); ok { m.Id = v }
}

type GetReservationArgsList []*GetReservationArgs

func (s *GetReservationArgsList) Len() int             { return len(*s) }
func (s *GetReservationArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *GetReservationArgsList) Append() model.Fielder  { v := &GetReservationArgs{}; *s = append(*s, v); return v }
func (s *GetReservationArgsList) IsNil() bool          { return s == nil }
func (s *GetReservationArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *GetReservationArgsList) DecodeFields(_ model.FieldReader) {}

func (m *GetReservationArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ListReservationsByStaffArgs struct {
	TenantId string
	StaffId string
	From int64
	To int64
}

func (m *ListReservationsByStaffArgs) ModelName() string { return "list_reservations_by_staff_args" }

func (m *ListReservationsByStaffArgs) Schema() []model.Field { return ListReservationsByStaffArgsModel.Fields }

func (m *ListReservationsByStaffArgs) Pointers() []any { return []any{&m.TenantId, &m.StaffId, &m.From, &m.To} }

func (m *ListReservationsByStaffArgs) IsNil() bool { return m == nil }

func (m *ListReservationsByStaffArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("staff_id", m.StaffId)
	w.Int("from", m.From)
	w.Int("to", m.To)
}

func (m *ListReservationsByStaffArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("staff_id"); ok { m.StaffId = v }
	if v, ok := r.Int("from"); ok { m.From = v }
	if v, ok := r.Int("to"); ok { m.To = v }
}

type ListReservationsByStaffArgsList []*ListReservationsByStaffArgs

func (s *ListReservationsByStaffArgsList) Len() int             { return len(*s) }
func (s *ListReservationsByStaffArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListReservationsByStaffArgsList) Append() model.Fielder  { v := &ListReservationsByStaffArgs{}; *s = append(*s, v); return v }
func (s *ListReservationsByStaffArgsList) IsNil() bool          { return s == nil }
func (s *ListReservationsByStaffArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListReservationsByStaffArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ListReservationsByStaffArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ListReservationsByClientArgs struct {
	TenantId string
	ClientId string
}

func (m *ListReservationsByClientArgs) ModelName() string { return "list_reservations_by_client_args" }

func (m *ListReservationsByClientArgs) Schema() []model.Field { return ListReservationsByClientArgsModel.Fields }

func (m *ListReservationsByClientArgs) Pointers() []any { return []any{&m.TenantId, &m.ClientId} }

func (m *ListReservationsByClientArgs) IsNil() bool { return m == nil }

func (m *ListReservationsByClientArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("client_id", m.ClientId)
}

func (m *ListReservationsByClientArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("client_id"); ok { m.ClientId = v }
}

type ListReservationsByClientArgsList []*ListReservationsByClientArgs

func (s *ListReservationsByClientArgsList) Len() int             { return len(*s) }
func (s *ListReservationsByClientArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListReservationsByClientArgsList) Append() model.Fielder  { v := &ListReservationsByClientArgs{}; *s = append(*s, v); return v }
func (s *ListReservationsByClientArgsList) IsNil() bool          { return s == nil }
func (s *ListReservationsByClientArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListReservationsByClientArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ListReservationsByClientArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ChangeReservationStatusArgs struct {
	TenantId string
	Id string
	Event string
	ActorId string
	PaymentId string
	Revision int64
}

func (m *ChangeReservationStatusArgs) ModelName() string { return "change_reservation_status_args" }

func (m *ChangeReservationStatusArgs) Schema() []model.Field { return ChangeReservationStatusArgsModel.Fields }

func (m *ChangeReservationStatusArgs) Pointers() []any { return []any{&m.TenantId, &m.Id, &m.Event, &m.ActorId, &m.PaymentId, &m.Revision} }

func (m *ChangeReservationStatusArgs) IsNil() bool { return m == nil }

func (m *ChangeReservationStatusArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("id", m.Id)
	w.String("event", m.Event)
	w.String("actor_id", m.ActorId)
	w.String("payment_id", m.PaymentId)
	w.Int("revision", m.Revision)
}

func (m *ChangeReservationStatusArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("event"); ok { m.Event = v }
	if v, ok := r.String("actor_id"); ok { m.ActorId = v }
	if v, ok := r.String("payment_id"); ok { m.PaymentId = v }
	if v, ok := r.Int("revision"); ok { m.Revision = v }
}

type ChangeReservationStatusArgsList []*ChangeReservationStatusArgs

func (s *ChangeReservationStatusArgsList) Len() int             { return len(*s) }
func (s *ChangeReservationStatusArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ChangeReservationStatusArgsList) Append() model.Fielder  { v := &ChangeReservationStatusArgs{}; *s = append(*s, v); return v }
func (s *ChangeReservationStatusArgsList) IsNil() bool          { return s == nil }
func (s *ChangeReservationStatusArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ChangeReservationStatusArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ChangeReservationStatusArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ExpirePendingReservationsArgs struct {
	TenantId string
	Before int64
}

func (m *ExpirePendingReservationsArgs) ModelName() string { return "expire_pending_reservations_args" }

func (m *ExpirePendingReservationsArgs) Schema() []model.Field { return ExpirePendingReservationsArgsModel.Fields }

func (m *ExpirePendingReservationsArgs) Pointers() []any { return []any{&m.TenantId, &m.Before} }

func (m *ExpirePendingReservationsArgs) IsNil() bool { return m == nil }

func (m *ExpirePendingReservationsArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.Int("before", m.Before)
}

func (m *ExpirePendingReservationsArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.Int("before"); ok { m.Before = v }
}

type ExpirePendingReservationsArgsList []*ExpirePendingReservationsArgs

func (s *ExpirePendingReservationsArgsList) Len() int             { return len(*s) }
func (s *ExpirePendingReservationsArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ExpirePendingReservationsArgsList) Append() model.Fielder  { v := &ExpirePendingReservationsArgs{}; *s = append(*s, v); return v }
func (s *ExpirePendingReservationsArgsList) IsNil() bool          { return s == nil }
func (s *ExpirePendingReservationsArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ExpirePendingReservationsArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ExpirePendingReservationsArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type UpsertCalendarConfigArgs struct {
	TenantId string
	StaffId string
	Timezone string
	IsActive bool
}

func (m *UpsertCalendarConfigArgs) ModelName() string { return "upsert_calendar_config_args" }

func (m *UpsertCalendarConfigArgs) Schema() []model.Field { return UpsertCalendarConfigArgsModel.Fields }

func (m *UpsertCalendarConfigArgs) Pointers() []any { return []any{&m.TenantId, &m.StaffId, &m.Timezone, &m.IsActive} }

func (m *UpsertCalendarConfigArgs) IsNil() bool { return m == nil }

func (m *UpsertCalendarConfigArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("staff_id", m.StaffId)
	w.String("timezone", m.Timezone)
	w.Bool("is_active", m.IsActive)
}

func (m *UpsertCalendarConfigArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("staff_id"); ok { m.StaffId = v }
	if v, ok := r.String("timezone"); ok { m.Timezone = v }
	if v, ok := r.Bool("is_active"); ok { m.IsActive = v }
}

type UpsertCalendarConfigArgsList []*UpsertCalendarConfigArgs

func (s *UpsertCalendarConfigArgsList) Len() int             { return len(*s) }
func (s *UpsertCalendarConfigArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *UpsertCalendarConfigArgsList) Append() model.Fielder  { v := &UpsertCalendarConfigArgs{}; *s = append(*s, v); return v }
func (s *UpsertCalendarConfigArgsList) IsNil() bool          { return s == nil }
func (s *UpsertCalendarConfigArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *UpsertCalendarConfigArgsList) DecodeFields(_ model.FieldReader) {}

func (m *UpsertCalendarConfigArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type SaveDayBlocksArgs struct {
	TenantId string
	StaffId string
	DayOfWeek int64
	Blocks []WorkCalendarBlock
}

func (m *SaveDayBlocksArgs) ModelName() string { return "save_day_blocks_args" }

func (m *SaveDayBlocksArgs) Schema() []model.Field { return SaveDayBlocksArgsModel.Fields }

func (m *SaveDayBlocksArgs) Pointers() []any { return []any{&m.TenantId, &m.StaffId, &m.DayOfWeek, &m.Blocks} }

func (m *SaveDayBlocksArgs) IsNil() bool { return m == nil }

func (m *SaveDayBlocksArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("staff_id", m.StaffId)
	w.Int("day_of_week", m.DayOfWeek)
		{
			arr := w.Array("blocks", len(m.Blocks))
			for _, x := range m.Blocks {
				arr.Object(&x)
			}
			arr.Close()
		}
}

func (m *SaveDayBlocksArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("staff_id"); ok { m.StaffId = v }
	if v, ok := r.Int("day_of_week"); ok { m.DayOfWeek = v }
	if arr, ok := r.Array("blocks"); ok {
		n := arr.Len()
		m.Blocks = make([]WorkCalendarBlock, n)
		for i := 0; i < n; i++ {
			arr.Object(i, &m.Blocks[i])
		}
	}
}

type SaveDayBlocksArgsList []*SaveDayBlocksArgs

func (s *SaveDayBlocksArgsList) Len() int             { return len(*s) }
func (s *SaveDayBlocksArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *SaveDayBlocksArgsList) Append() model.Fielder  { v := &SaveDayBlocksArgs{}; *s = append(*s, v); return v }
func (s *SaveDayBlocksArgsList) IsNil() bool          { return s == nil }
func (s *SaveDayBlocksArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *SaveDayBlocksArgsList) DecodeFields(_ model.FieldReader) {}

func (m *SaveDayBlocksArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type SaveDateBlocksArgs struct {
	TenantId string
	StaffId string
	SpecificDate int64
	Blocks []WorkCalendarBlock
}

func (m *SaveDateBlocksArgs) ModelName() string { return "save_date_blocks_args" }

func (m *SaveDateBlocksArgs) Schema() []model.Field { return SaveDateBlocksArgsModel.Fields }

func (m *SaveDateBlocksArgs) Pointers() []any { return []any{&m.TenantId, &m.StaffId, &m.SpecificDate, &m.Blocks} }

func (m *SaveDateBlocksArgs) IsNil() bool { return m == nil }

func (m *SaveDateBlocksArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("staff_id", m.StaffId)
	w.Int("specific_date", m.SpecificDate)
		{
			arr := w.Array("blocks", len(m.Blocks))
			for _, x := range m.Blocks {
				arr.Object(&x)
			}
			arr.Close()
		}
}

func (m *SaveDateBlocksArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("staff_id"); ok { m.StaffId = v }
	if v, ok := r.Int("specific_date"); ok { m.SpecificDate = v }
	if arr, ok := r.Array("blocks"); ok {
		n := arr.Len()
		m.Blocks = make([]WorkCalendarBlock, n)
		for i := 0; i < n; i++ {
			arr.Object(i, &m.Blocks[i])
		}
	}
}

type SaveDateBlocksArgsList []*SaveDateBlocksArgs

func (s *SaveDateBlocksArgsList) Len() int             { return len(*s) }
func (s *SaveDateBlocksArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *SaveDateBlocksArgsList) Append() model.Fielder  { v := &SaveDateBlocksArgs{}; *s = append(*s, v); return v }
func (s *SaveDateBlocksArgsList) IsNil() bool          { return s == nil }
func (s *SaveDateBlocksArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *SaveDateBlocksArgsList) DecodeFields(_ model.FieldReader) {}

func (m *SaveDateBlocksArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type MarkWorkingDaysArgs struct {
	TenantId string
	StaffId string
	Dates []int
	StartMin int64
	EndMin int64
}

func (m *MarkWorkingDaysArgs) ModelName() string { return "mark_working_days_args" }

func (m *MarkWorkingDaysArgs) Schema() []model.Field { return MarkWorkingDaysArgsModel.Fields }

func (m *MarkWorkingDaysArgs) Pointers() []any { return []any{&m.TenantId, &m.StaffId, &m.Dates, &m.StartMin, &m.EndMin} }

func (m *MarkWorkingDaysArgs) IsNil() bool { return m == nil }

func (m *MarkWorkingDaysArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("staff_id", m.StaffId)
		{
			arr := w.Array("dates", len(m.Dates))
			for _, x := range m.Dates {
				arr.Int(int64(x))
			}
			arr.Close()
		}
	w.Int("start_min", m.StartMin)
	w.Int("end_min", m.EndMin)
}

func (m *MarkWorkingDaysArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("staff_id"); ok { m.StaffId = v }
	if arr, ok := r.Array("dates"); ok {
		n := arr.Len()
		m.Dates = make([]int, n)
		for i := 0; i < n; i++ {
			m.Dates[i] = int(arr.Int(i))
		}
	}
	if v, ok := r.Int("start_min"); ok { m.StartMin = v }
	if v, ok := r.Int("end_min"); ok { m.EndMin = v }
}

type MarkWorkingDaysArgsList []*MarkWorkingDaysArgs

func (s *MarkWorkingDaysArgsList) Len() int             { return len(*s) }
func (s *MarkWorkingDaysArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *MarkWorkingDaysArgsList) Append() model.Fielder  { v := &MarkWorkingDaysArgs{}; *s = append(*s, v); return v }
func (s *MarkWorkingDaysArgsList) IsNil() bool          { return s == nil }
func (s *MarkWorkingDaysArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *MarkWorkingDaysArgsList) DecodeFields(_ model.FieldReader) {}

func (m *MarkWorkingDaysArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type UnmarkWorkingDaysArgs struct {
	TenantId string
	StaffId string
	Dates []int
}

func (m *UnmarkWorkingDaysArgs) ModelName() string { return "unmark_working_days_args" }

func (m *UnmarkWorkingDaysArgs) Schema() []model.Field { return UnmarkWorkingDaysArgsModel.Fields }

func (m *UnmarkWorkingDaysArgs) Pointers() []any { return []any{&m.TenantId, &m.StaffId, &m.Dates} }

func (m *UnmarkWorkingDaysArgs) IsNil() bool { return m == nil }

func (m *UnmarkWorkingDaysArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("staff_id", m.StaffId)
		{
			arr := w.Array("dates", len(m.Dates))
			for _, x := range m.Dates {
				arr.Int(int64(x))
			}
			arr.Close()
		}
}

func (m *UnmarkWorkingDaysArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("staff_id"); ok { m.StaffId = v }
	if arr, ok := r.Array("dates"); ok {
		n := arr.Len()
		m.Dates = make([]int, n)
		for i := 0; i < n; i++ {
			m.Dates[i] = int(arr.Int(i))
		}
	}
}

type UnmarkWorkingDaysArgsList []*UnmarkWorkingDaysArgs

func (s *UnmarkWorkingDaysArgsList) Len() int             { return len(*s) }
func (s *UnmarkWorkingDaysArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *UnmarkWorkingDaysArgsList) Append() model.Fielder  { v := &UnmarkWorkingDaysArgs{}; *s = append(*s, v); return v }
func (s *UnmarkWorkingDaysArgsList) IsNil() bool          { return s == nil }
func (s *UnmarkWorkingDaysArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *UnmarkWorkingDaysArgsList) DecodeFields(_ model.FieldReader) {}

func (m *UnmarkWorkingDaysArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ListBlocksArgs struct {
	TenantId string
	StaffId string
}

func (m *ListBlocksArgs) ModelName() string { return "list_blocks_args" }

func (m *ListBlocksArgs) Schema() []model.Field { return ListBlocksArgsModel.Fields }

func (m *ListBlocksArgs) Pointers() []any { return []any{&m.TenantId, &m.StaffId} }

func (m *ListBlocksArgs) IsNil() bool { return m == nil }

func (m *ListBlocksArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("staff_id", m.StaffId)
}

func (m *ListBlocksArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("staff_id"); ok { m.StaffId = v }
}

type ListBlocksArgsList []*ListBlocksArgs

func (s *ListBlocksArgsList) Len() int             { return len(*s) }
func (s *ListBlocksArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListBlocksArgsList) Append() model.Fielder  { v := &ListBlocksArgs{}; *s = append(*s, v); return v }
func (s *ListBlocksArgsList) IsNil() bool          { return s == nil }
func (s *ListBlocksArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListBlocksArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ListBlocksArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type GetDayBoundsArgs struct {
	TenantId string
	Date int64
}

func (m *GetDayBoundsArgs) ModelName() string { return "get_day_bounds_args" }

func (m *GetDayBoundsArgs) Schema() []model.Field { return GetDayBoundsArgsModel.Fields }

func (m *GetDayBoundsArgs) Pointers() []any { return []any{&m.TenantId, &m.Date} }

func (m *GetDayBoundsArgs) IsNil() bool { return m == nil }

func (m *GetDayBoundsArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.Int("date", m.Date)
}

func (m *GetDayBoundsArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.Int("date"); ok { m.Date = v }
}

type GetDayBoundsArgsList []*GetDayBoundsArgs

func (s *GetDayBoundsArgsList) Len() int             { return len(*s) }
func (s *GetDayBoundsArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *GetDayBoundsArgsList) Append() model.Fielder  { v := &GetDayBoundsArgs{}; *s = append(*s, v); return v }
func (s *GetDayBoundsArgsList) IsNil() bool          { return s == nil }
func (s *GetDayBoundsArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *GetDayBoundsArgsList) DecodeFields(_ model.FieldReader) {}

func (m *GetDayBoundsArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ListConflictingReservationsArgs struct {
	TenantId string
	StaffId string
	From int64
}

func (m *ListConflictingReservationsArgs) ModelName() string { return "list_conflicting_reservations_args" }

func (m *ListConflictingReservationsArgs) Schema() []model.Field { return ListConflictingReservationsArgsModel.Fields }

func (m *ListConflictingReservationsArgs) Pointers() []any { return []any{&m.TenantId, &m.StaffId, &m.From} }

func (m *ListConflictingReservationsArgs) IsNil() bool { return m == nil }

func (m *ListConflictingReservationsArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("staff_id", m.StaffId)
	w.Int("from", m.From)
}

func (m *ListConflictingReservationsArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("staff_id"); ok { m.StaffId = v }
	if v, ok := r.Int("from"); ok { m.From = v }
}

type ListConflictingReservationsArgsList []*ListConflictingReservationsArgs

func (s *ListConflictingReservationsArgsList) Len() int             { return len(*s) }
func (s *ListConflictingReservationsArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListConflictingReservationsArgsList) Append() model.Fielder  { v := &ListConflictingReservationsArgs{}; *s = append(*s, v); return v }
func (s *ListConflictingReservationsArgsList) IsNil() bool          { return s == nil }
func (s *ListConflictingReservationsArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListConflictingReservationsArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ListConflictingReservationsArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type RecomputeConflictsArgs struct {
	TenantId string
	From int64
	To int64
}

func (m *RecomputeConflictsArgs) ModelName() string { return "recompute_conflicts_args" }

func (m *RecomputeConflictsArgs) Schema() []model.Field { return RecomputeConflictsArgsModel.Fields }

func (m *RecomputeConflictsArgs) Pointers() []any { return []any{&m.TenantId, &m.From, &m.To} }

func (m *RecomputeConflictsArgs) IsNil() bool { return m == nil }

func (m *RecomputeConflictsArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.Int("from", m.From)
	w.Int("to", m.To)
}

func (m *RecomputeConflictsArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.Int("from"); ok { m.From = v }
	if v, ok := r.Int("to"); ok { m.To = v }
}

type RecomputeConflictsArgsList []*RecomputeConflictsArgs

func (s *RecomputeConflictsArgsList) Len() int             { return len(*s) }
func (s *RecomputeConflictsArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *RecomputeConflictsArgsList) Append() model.Fielder  { v := &RecomputeConflictsArgs{}; *s = append(*s, v); return v }
func (s *RecomputeConflictsArgsList) IsNil() bool          { return s == nil }
func (s *RecomputeConflictsArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *RecomputeConflictsArgsList) DecodeFields(_ model.FieldReader) {}

func (m *RecomputeConflictsArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ConflictingReservation struct {
	ReservationId string
	StartsAt int64
	ClientId string
	Reason string
}

func (m *ConflictingReservation) ModelName() string { return "conflicting_reservation" }

func (m *ConflictingReservation) Schema() []model.Field { return ConflictingReservationModel.Fields }

func (m *ConflictingReservation) Pointers() []any { return []any{&m.ReservationId, &m.StartsAt, &m.ClientId, &m.Reason} }

func (m *ConflictingReservation) IsNil() bool { return m == nil }

func (m *ConflictingReservation) EncodeFields(w model.FieldWriter) {
	w.String("reservation_id", m.ReservationId)
	w.Int("starts_at", m.StartsAt)
	w.String("client_id", m.ClientId)
	w.String("reason", m.Reason)
}

func (m *ConflictingReservation) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("reservation_id"); ok { m.ReservationId = v }
	if v, ok := r.Int("starts_at"); ok { m.StartsAt = v }
	if v, ok := r.String("client_id"); ok { m.ClientId = v }
	if v, ok := r.String("reason"); ok { m.Reason = v }
}

type ConflictingReservationList []*ConflictingReservation

func (s *ConflictingReservationList) Len() int             { return len(*s) }
func (s *ConflictingReservationList) At(i int) model.Fielder { return (*s)[i] }
func (s *ConflictingReservationList) Append() model.Fielder  { v := &ConflictingReservation{}; *s = append(*s, v); return v }
func (s *ConflictingReservationList) IsNil() bool          { return s == nil }
func (s *ConflictingReservationList) EncodeFields(_ model.FieldWriter) {}
func (s *ConflictingReservationList) DecodeFields(_ model.FieldReader) {}

func (m *ConflictingReservation) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type DayBoundsResult struct {
	Open bool
	OpenMin int64
	CloseMin int64
}

func (m *DayBoundsResult) ModelName() string { return "day_bounds_result" }

func (m *DayBoundsResult) Schema() []model.Field { return DayBoundsResultModel.Fields }

func (m *DayBoundsResult) Pointers() []any { return []any{&m.Open, &m.OpenMin, &m.CloseMin} }

func (m *DayBoundsResult) IsNil() bool { return m == nil }

func (m *DayBoundsResult) EncodeFields(w model.FieldWriter) {
	w.Bool("open", m.Open)
	w.Int("open_min", m.OpenMin)
	w.Int("close_min", m.CloseMin)
}

func (m *DayBoundsResult) DecodeFields(r model.FieldReader) {
	if v, ok := r.Bool("open"); ok { m.Open = v }
	if v, ok := r.Int("open_min"); ok { m.OpenMin = v }
	if v, ok := r.Int("close_min"); ok { m.CloseMin = v }
}

type DayBoundsResultList []*DayBoundsResult

func (s *DayBoundsResultList) Len() int             { return len(*s) }
func (s *DayBoundsResultList) At(i int) model.Fielder { return (*s)[i] }
func (s *DayBoundsResultList) Append() model.Fielder  { v := &DayBoundsResult{}; *s = append(*s, v); return v }
func (s *DayBoundsResultList) IsNil() bool          { return s == nil }
func (s *DayBoundsResultList) EncodeFields(_ model.FieldWriter) {}
func (s *DayBoundsResultList) DecodeFields(_ model.FieldReader) {}

func (m *DayBoundsResult) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type AddCalendarExceptionArgs struct {
	TenantId string
	StaffId string
	SpecificDate int64
	ExceptionType string
	StartTime int64
	EndTime int64
	Notes string
}

func (m *AddCalendarExceptionArgs) ModelName() string { return "add_calendar_exception_args" }

func (m *AddCalendarExceptionArgs) Schema() []model.Field { return AddCalendarExceptionArgsModel.Fields }

func (m *AddCalendarExceptionArgs) Pointers() []any { return []any{&m.TenantId, &m.StaffId, &m.SpecificDate, &m.ExceptionType, &m.StartTime, &m.EndTime, &m.Notes} }

func (m *AddCalendarExceptionArgs) IsNil() bool { return m == nil }

func (m *AddCalendarExceptionArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("staff_id", m.StaffId)
	w.Int("specific_date", m.SpecificDate)
	w.String("exception_type", m.ExceptionType)
	w.Int("start_time", m.StartTime)
	w.Int("end_time", m.EndTime)
	w.String("notes", m.Notes)
}

func (m *AddCalendarExceptionArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("staff_id"); ok { m.StaffId = v }
	if v, ok := r.Int("specific_date"); ok { m.SpecificDate = v }
	if v, ok := r.String("exception_type"); ok { m.ExceptionType = v }
	if v, ok := r.Int("start_time"); ok { m.StartTime = v }
	if v, ok := r.Int("end_time"); ok { m.EndTime = v }
	if v, ok := r.String("notes"); ok { m.Notes = v }
}

type AddCalendarExceptionArgsList []*AddCalendarExceptionArgs

func (s *AddCalendarExceptionArgsList) Len() int             { return len(*s) }
func (s *AddCalendarExceptionArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *AddCalendarExceptionArgsList) Append() model.Fielder  { v := &AddCalendarExceptionArgs{}; *s = append(*s, v); return v }
func (s *AddCalendarExceptionArgsList) IsNil() bool          { return s == nil }
func (s *AddCalendarExceptionArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *AddCalendarExceptionArgsList) DecodeFields(_ model.FieldReader) {}

func (m *AddCalendarExceptionArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type RemoveCalendarExceptionArgs struct {
	TenantId string
	ExceptionId string
}

func (m *RemoveCalendarExceptionArgs) ModelName() string { return "remove_calendar_exception_args" }

func (m *RemoveCalendarExceptionArgs) Schema() []model.Field { return RemoveCalendarExceptionArgsModel.Fields }

func (m *RemoveCalendarExceptionArgs) Pointers() []any { return []any{&m.TenantId, &m.ExceptionId} }

func (m *RemoveCalendarExceptionArgs) IsNil() bool { return m == nil }

func (m *RemoveCalendarExceptionArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("exception_id", m.ExceptionId)
}

func (m *RemoveCalendarExceptionArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("exception_id"); ok { m.ExceptionId = v }
}

type RemoveCalendarExceptionArgsList []*RemoveCalendarExceptionArgs

func (s *RemoveCalendarExceptionArgsList) Len() int             { return len(*s) }
func (s *RemoveCalendarExceptionArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *RemoveCalendarExceptionArgsList) Append() model.Fielder  { v := &RemoveCalendarExceptionArgs{}; *s = append(*s, v); return v }
func (s *RemoveCalendarExceptionArgsList) IsNil() bool          { return s == nil }
func (s *RemoveCalendarExceptionArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *RemoveCalendarExceptionArgsList) DecodeFields(_ model.FieldReader) {}

func (m *RemoveCalendarExceptionArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ListAvailabilityArgs struct {
	TenantId string
	StaffId string
	ConfigId string
	From int64
	To int64
}

func (m *ListAvailabilityArgs) ModelName() string { return "list_availability_args" }

func (m *ListAvailabilityArgs) Schema() []model.Field { return ListAvailabilityArgsModel.Fields }

func (m *ListAvailabilityArgs) Pointers() []any { return []any{&m.TenantId, &m.StaffId, &m.ConfigId, &m.From, &m.To} }

func (m *ListAvailabilityArgs) IsNil() bool { return m == nil }

func (m *ListAvailabilityArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("staff_id", m.StaffId)
	w.String("config_id", m.ConfigId)
	w.Int("from", m.From)
	w.Int("to", m.To)
}

func (m *ListAvailabilityArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("staff_id"); ok { m.StaffId = v }
	if v, ok := r.String("config_id"); ok { m.ConfigId = v }
	if v, ok := r.Int("from"); ok { m.From = v }
	if v, ok := r.Int("to"); ok { m.To = v }
}

type ListAvailabilityArgsList []*ListAvailabilityArgs

func (s *ListAvailabilityArgsList) Len() int             { return len(*s) }
func (s *ListAvailabilityArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListAvailabilityArgsList) Append() model.Fielder  { v := &ListAvailabilityArgs{}; *s = append(*s, v); return v }
func (s *ListAvailabilityArgsList) IsNil() bool          { return s == nil }
func (s *ListAvailabilityArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListAvailabilityArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ListAvailabilityArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ListExceptionsArgs struct {
	TenantId string
	StaffId string
	From int64
	To int64
}

func (m *ListExceptionsArgs) ModelName() string { return "list_exceptions_args" }

func (m *ListExceptionsArgs) Schema() []model.Field { return ListExceptionsArgsModel.Fields }

func (m *ListExceptionsArgs) Pointers() []any { return []any{&m.TenantId, &m.StaffId, &m.From, &m.To} }

func (m *ListExceptionsArgs) IsNil() bool { return m == nil }

func (m *ListExceptionsArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("staff_id", m.StaffId)
	w.Int("from", m.From)
	w.Int("to", m.To)
}

func (m *ListExceptionsArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("staff_id"); ok { m.StaffId = v }
	if v, ok := r.Int("from"); ok { m.From = v }
	if v, ok := r.Int("to"); ok { m.To = v }
}

type ListExceptionsArgsList []*ListExceptionsArgs

func (s *ListExceptionsArgsList) Len() int             { return len(*s) }
func (s *ListExceptionsArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListExceptionsArgsList) Append() model.Fielder  { v := &ListExceptionsArgs{}; *s = append(*s, v); return v }
func (s *ListExceptionsArgsList) IsNil() bool          { return s == nil }
func (s *ListExceptionsArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListExceptionsArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ListExceptionsArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

